### ISSUE TITLE
translations.txt cause web page empty

### ISSUE THREAD

**Issue by lhy2871** [unraid/lang-zh_CN#126]
I updated to newst zh_CN translate.
I got an empty webGUI. pic attached.
<img width="1440" alt="Screenshot 2023-12-02 at 19 28 53" src="https://github.com/unraid/lang-zh_CN/assets/10602576/59cfe1c9-8aca-4aac-9d71-404895223d5b">
I try to figure out the bug.
I found if I delete the translations.txt file at /usr/local/emhttp/languages/zh_CN, the webGUI will show the right things. pic attached
<img width="728" alt="Screenshot 2023-12-02 at 19 36 02" src="https://github.com/unraid/lang-zh_CN/assets/10602576/75bc3853-ecb4-4850-a839-5b2b66c49094">
I tried to save this file as UTF-8 encode.
I tried to split this file into 500 lines, and every part of file will cause empty web.
I tried delete this file and 'touch translations.txt', still got empty webGUI.
I am powerless.
Someone could help?

**Comment by fuliaojiyue** [comment]
我也是出现这种错误，现在更新unraid6.12.6看看还会不会出现

**Comment by fuliaojiyue** [comment]
我找到错误的地方了，在translations.txt里的1079行`Trial Key Expires in %s=试用密钥将在%过期`这段代码，删除就恢复正常了
